name: keebie
description: The virtual keyboard for ExpidusOS.
publish_to: 'none'
version: 0.1.0+1
homepage: https://expidusos.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: feat/packages
      path: packages/libtokyo
  libtokyo_flutter:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      ref: feat/packages
      path: packages/libtokyo_flutter
  pubspec: ^2.3.0
  sentry_flutter: ^7.6.3
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/
    - pubspec.yaml